name: Build and Release Pupil-com

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Dependencies Installation
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Generate credentials.json securely
      shell: bash
      env:
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: echo "$GOOGLE_CREDS" > credentials.json

    - name: Executable build with PyInstaller
      run: >
        pyinstaller --onefile --windowed --name "Pupil-com"
        --exclude-module PySide6 
        --exclude-module shiboken6 
        --collect-data autocorrect 
        --collect-data wordfreq 
        --collect-data mediapipe 
        --add-data "credentials.json;." 
        --add-data "Images;Images" 
        --add-data "Sounds;Sounds" 
        main.py

    - name: Executable build on the Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/Pupil-com.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
